#+TITLE: [[http://www.andermikalson.com][Ander Mikalson]]
#+DATE: 16 April 2019
#+SUBTITLE: Spring 2019 VA&T Lecture Series
#+OPTIONS: toc:nil num:nil

Ander Mikalson's work, /Scores for a Black Hole/, is a work of performance art with an interesting backdrop. She involves collaborators and artists to perform, not in the company of, but instead TO a pitch black, seven-foot hole in the ground. The hole is filled with a highly reflective black ink, creating the illusion of the hole being infinite. Some performances included playing astronomy lectures to the black hole, reading emails to it, performing comedy to it, and other such performances. The installation is surrounded by black and white drawings, which serve as an archive of the performances that have occured in the company of the black hole. The art, performances, and archives are all extremely minimal and restrained. Under this mode of operation, no two visits to the exhibit are the same. 

This performance excited me in that the artist invoked the scientific nature of the piece, by inviting in performers and creating a sort of /gravity/ around the black hole. I am fascinated by how she was able to turn artists into performers by having them work in an intimate context with the black hole. I was unsure of how being in the presence of the black hole helped the performers to develop, as she mentioned in her talk. In spite of this, this artist has helped me broaden my definition of performance art, and get more creative about the ways in which I can bring the undertones of a piece to life.
